security:
  oauth2:
    client:
      client-id: applister
      client-secret: secret
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
      token-name: oauth_token
      authentication-scheme: header
      client-authentication-scheme: header
    resource:
      user-info-uri: http://localhost:8080/uaa/userinfo
server:
  port: 8888